Content Tag Registry
satisfactorymodding/SatisfactoryModLoader pull request #273
Opened 2024-08-21 22:00 UTC by budak7273

Implementation of #271 

See https://discord.com/channels/555424930502541343/1268324829463969832

2024-08-21 22:01 UTC, budak7273 commented on Mods/SML/Source/SML/Private/Registry/ModContentRegistry.cpp
> +			// TODO switch over to Content Tag Registry
Investigating how best to get a reference to the subsystem from here

2024-08-29 07:26 UTC, mircearoata requested changes

2024-09-01 18:53 UTC, budak7273 commented on Mods/SML/Source/SML/Private/Registry/ContentTagRegistry.cpp
> +}
I would rather stop it early to avoid processing a ton of tag adds that are known to fail

2024-09-06 12:45 UTC, mircearoata approved these changes

2024-09-06 14:51 UTC, merged